---
- hosts: all

  tasks:
   - name: Install packages
     yum:
      name: 
        - epel-release
        - httpd
        - firewalld
      state: latest

   - name: Copy index.html
     copy:
      content: "Welcome to my web server"
      dest: /var/www/html/index.html
      force: no
      mode: 0444

   - name: Start service httpd, if not started
     service:
      name: httpd
      state: started

   - name: Configure firewalld
     firewalld:
       service: http
       permanent: yes
       state: enabled
...