---
- hosts: all
  tasks:
   - name: Ensure SELinux is set to enforcing mode
     lineinfile:
       path: /etc/default/grub
       backrefs: yes
       regexp: '^(GRUB_CMDLINE_LINUX=(?!.* net.ifnames=)\"[^\"]+)(\".*)'
       line: 'net.ifnames=1'
...