---
- hosts: all
  tasks:
   - name: Ensure SELinux is set to enforcing mode
     lineinfile:
       path: /etc/default/grub
       regexp: '^(GRUB_CMDLINE_LINUX=(?!.* net.ifnames)\"[^\"]+)(\".*)'
       line: '\1 net.ifnames=1\2'
...